steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      - kms
      - decrypt
      - --ciphertext-file
      - AZURE_PAT_PROD.txt.enc
      - --plaintext-file
      - AZURE_PAT_PROD.txt
      - --location
      - us-central1
      - --keyring
      - attach-key-ring
      - --key
      - azure-devops-commits
    id: decrypt azure_pat_prod
  - name: gcr.io/cloud-builders/gcloud
    args:
      - kms
      - decrypt
      - --ciphertext-file
      - GOOGLE_CLOUD_PROJECT_ID.txt.enc
      - --plaintext-file
      - GOOGLE_CLOUD_PROJECT_ID.txt
      - --location
      - us-central1
      - --keyring
      - attach-key-ring
      - --key
      - azure-devops-commits
    id: decrypt gc_proj_id
  - name: gcr.io/cloud-builders/gcloud
    args:
      - kms
      - decrypt
      - --ciphertext-file
      - attach-commits-fa50e59d273d.json.enc
      - --plaintext-file
      - attach-commits-fa50e59d273d.json
      - --location
      - us-central1
      - --keyring
      - attach-key-ring
      - --key
      - azure-devops-commits
    id: decrypt gsa_path
  - name: gcr.io/cloud-builders/gcloud
    args:
      - kms
      - decrypt
      - --ciphertext-file
      - GOOGLE_BIGQUERY_DATASET_NAME.TXT.enc
      - --plaintext-file
      - GOOGLE_BIGQUERY_DATASET_NAME.TXT
      - --location
      - us-central1
      - --keyring
      - attach-key-ring
      - --key
      - azure-devops-commits
    id: decrypt dataset_name
  - name: gcr.io/cloud-builders/gcloud
    args:
      - kms
      - decrypt
      - --ciphertext-file
      - GOOGLE_BIGQUERY_TABLE_NAME.txt.enc
      - --plaintext-file
      - GOOGLE_BIGQUERY_TABLE_NAME.txt
      - --location
      - us-central1
      - --keyring
      - attach-key-ring
      - --key
      - azure-devops-commits
    id: decrypt table_name
  - name: rocker/verse:3.6.1
    args:
      - Rscript

      - map.r
    waitFor:
      - decrypt gsa_path
timeout: 900s
