
AZURE_PAT <- read_file("AZURE_PAT.txt")
GOOGLE_CLOUD_PROJECT_ID <- read_file("GOOGLE_CLOUD_PROJECT_ID.txt")
GOOGLE_BIGQUERY_TABLE_NAME <- read_file("GOOGLE_BIGQUERY_TABLE_NAME.txt")
GOOGLE_BIGQUERY_DATASET_NAME <- read_file("GOOGLE_BIGQUERY_DATASET_NAME.TXT")
#GCS_DEFAULT_BUCKET <- read.table(file = "GCS_DEFAULT_BUCKET.txt")
#CR_REGION <- read.table(file = "CR_REGION.txt")
#CR_BUILD_EMAIL <- read.table(file = "CR_BUILD_EMAIL.txt")
GOOGLE_SERVICE_ACCOUNT_PATH <- c("attach-commits-fa50e59d273d.json") 
